-- Migration number: 0001 	 2026-08-10T05:20:33.644Z
-- Registration data foundation for Cloudflare D1.
-- IDs and timestamps are generated by application code as opaque TEXT IDs and
-- UTC ISO-8601 strings. Do not expose SQLite rowids as public identifiers.

CREATE TABLE guardian_account (
  id TEXT PRIMARY KEY,
  full_name TEXT NOT NULL,
  primary_phone TEXT NOT NULL,
  primary_phone_normalized TEXT NOT NULL,
  secondary_phone TEXT,
  secondary_phone_normalized TEXT,
  email TEXT NOT NULL,
  email_normalized TEXT NOT NULL,
  facebook_name TEXT,
  home_address TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'needs_review', 'archived')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (length(trim(full_name)) > 0),
  CHECK (length(trim(primary_phone)) > 0),
  CHECK (length(trim(email)) > 0),
  CHECK (length(trim(home_address)) > 0),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE student (
  id TEXT PRIMARY KEY,
  surname TEXT NOT NULL,
  given_name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('female', 'male', 'not_specified')),
  date_of_birth TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (length(trim(surname)) > 0),
  CHECK (length(trim(given_name)) > 0),
  CHECK (length(date_of_birth) = 10),
  CHECK (substr(date_of_birth, 5, 1) = '-'),
  CHECK (substr(date_of_birth, 8, 1) = '-'),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE guardian_student_relationship (
  id TEXT PRIMARY KEY,
  guardian_id TEXT NOT NULL REFERENCES guardian_account(id) ON DELETE RESTRICT,
  student_id TEXT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
  relationship_label TEXT NOT NULL,
  is_authorized_to_register INTEGER NOT NULL DEFAULT 1 CHECK (is_authorized_to_register IN (0, 1)),
  status TEXT NOT NULL CHECK (status IN ('active', 'needs_review', 'ended')),
  starts_on TEXT,
  ends_on TEXT,
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (guardian_id, student_id, relationship_label),
  CHECK (length(trim(relationship_label)) > 0),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE family_group (
  id TEXT PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('active', 'needs_review', 'archived')),
  source TEXT NOT NULL CHECK (source IN ('guardian_declared', 'admin_confirmed', 'test_fixture')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE family_group_member (
  id TEXT PRIMARY KEY,
  family_group_id TEXT NOT NULL REFERENCES family_group(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
  guardian_id TEXT REFERENCES guardian_account(id) ON DELETE RESTRICT,
  relationship_basis TEXT NOT NULL CHECK (relationship_basis IN ('guardian_declared', 'admin_confirmed', 'test_fixture')),
  status TEXT NOT NULL CHECK (status IN ('active', 'removed')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (family_group_id, student_id),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE academic_year (
  id TEXT PRIMARY KEY,
  public_label TEXT NOT NULL,
  registration_status TEXT NOT NULL CHECK (registration_status IN ('draft', 'open', 'closed', 'archived')),
  starts_on TEXT,
  ends_on TEXT,
  is_current INTEGER NOT NULL DEFAULT 0 CHECK (is_current IN (0, 1)),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (length(trim(public_label)) > 0),
  CHECK (starts_on IS NULL OR length(starts_on) = 10),
  CHECK (ends_on IS NULL OR length(ends_on) = 10),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE class_session (
  id TEXT PRIMARY KEY,
  academic_year_id TEXT NOT NULL REFERENCES academic_year(id) ON DELETE RESTRICT,
  stage_code TEXT NOT NULL CHECK (stage_code IN ('stage_1', 'stage_2', 'stage_3')),
  display_label TEXT NOT NULL,
  weekday TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  status TEXT NOT NULL CHECK (status IN ('draft', 'available', 'full', 'closed', 'cancelled')),
  facebook_group_url TEXT,
  is_test_only INTEGER NOT NULL DEFAULT 0 CHECK (is_test_only IN (0, 1)),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (academic_year_id, stage_code, weekday, start_time, end_time),
  CHECK (length(trim(display_label)) > 0),
  CHECK (length(start_time) = 5),
  CHECK (length(end_time) = 5),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE pre_registration (
  id TEXT PRIMARY KEY,
  guardian_id TEXT NOT NULL REFERENCES guardian_account(id) ON DELETE RESTRICT,
  academic_year_id TEXT NOT NULL REFERENCES academic_year(id) ON DELETE RESTRICT,
  family_group_id TEXT REFERENCES family_group(id) ON DELETE SET NULL,
  status TEXT NOT NULL CHECK (status IN ('draft', 'submitted', 'under_review', 'awaiting_assignment', 'cancelled', 'completed')),
  access_state_ref TEXT,
  submitted_at TEXT,
  cancelled_at TEXT,
  deletion_requested_at TEXT,
  deleted_at TEXT,
  hard_delete_allowed INTEGER NOT NULL DEFAULT 0 CHECK (hard_delete_allowed IN (0, 1)),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE application_child (
  id TEXT PRIMARY KEY,
  pre_registration_id TEXT NOT NULL REFERENCES pre_registration(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
  current_school TEXT,
  current_grade INTEGER NOT NULL CHECK (current_grade BETWEEN 1 AND 12),
  returning_status TEXT NOT NULL CHECK (returning_status IN ('new', 'returning', 'unknown')),
  previous_stage_code TEXT CHECK (previous_stage_code IS NULL OR previous_stage_code IN ('stage_1', 'stage_2', 'stage_3')),
  referral_code_input TEXT,
  selected_payment_plan_code TEXT,
  status TEXT NOT NULL CHECK (status IN ('submitted', 'needs_review', 'hold_created', 'waitlisted', 'enrolled', 'cancelled')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (pre_registration_id, student_id),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE ranked_class_preference (
  id TEXT PRIMARY KEY,
  application_child_id TEXT NOT NULL REFERENCES application_child(id) ON DELETE CASCADE,
  class_session_id TEXT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
  preference_rank INTEGER NOT NULL CHECK (preference_rank > 0),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (application_child_id, preference_rank),
  UNIQUE (application_child_id, class_session_id)
);

CREATE TABLE enrollment (
  id TEXT PRIMARY KEY,
  application_child_id TEXT NOT NULL UNIQUE REFERENCES application_child(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES student(id) ON DELETE RESTRICT,
  academic_year_id TEXT NOT NULL REFERENCES academic_year(id) ON DELETE RESTRICT,
  class_session_id TEXT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN ('awaiting_initial_payment', 'confirmed', 'initial_hold_expired', 'cancelled', 'completed')),
  initial_hold_created_at TEXT,
  original_hold_deadline_at TEXT,
  effective_hold_deadline_at TEXT,
  confirmed_at TEXT,
  cancelled_at TEXT,
  completed_at TEXT,
  cancellation_reason TEXT,
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE waitlist_entry (
  id TEXT PRIMARY KEY,
  application_child_id TEXT NOT NULL REFERENCES application_child(id) ON DELETE CASCADE,
  class_session_id TEXT NOT NULL REFERENCES class_session(id) ON DELETE RESTRICT,
  preference_rank INTEGER NOT NULL CHECK (preference_rank > 0),
  priority_note TEXT,
  status TEXT NOT NULL CHECK (status IN ('active', 'offered', 'offer_expired', 'accepted', 'deactivated', 'cancelled')),
  offered_at TEXT,
  offer_expires_at TEXT,
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (application_child_id, class_session_id),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE referral (
  id TEXT PRIMARY KEY,
  referral_code TEXT NOT NULL,
  referring_enrollment_id TEXT REFERENCES enrollment(id) ON DELETE SET NULL,
  referring_student_id TEXT REFERENCES student(id) ON DELETE SET NULL,
  referred_application_child_id TEXT NOT NULL REFERENCES application_child(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'qualified', 'disqualified', 'cancelled')),
  qualification_reason TEXT,
  qualified_at TEXT,
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (referral_code, referred_application_child_id),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE outbound_email (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  template_key TEXT NOT NULL,
  guardian_id TEXT REFERENCES guardian_account(id) ON DELETE SET NULL,
  pre_registration_id TEXT REFERENCES pre_registration(id) ON DELETE SET NULL,
  enrollment_id TEXT REFERENCES enrollment(id) ON DELETE SET NULL,
  intended_to_email TEXT NOT NULL,
  actual_delivery_email TEXT,
  delivery_mode TEXT NOT NULL CHECK (delivery_mode IN ('production', 'staging_override', 'test_override')),
  status TEXT NOT NULL CHECK (status IN ('queued', 'sent', 'failed', 'cancelled')),
  provider_message_id TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  queued_at TEXT NOT NULL,
  sent_at TEXT,
  failed_at TEXT,
  context_json TEXT,
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (context_json IS NULL OR json_valid(context_json)),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE TABLE audit_event (
  id TEXT PRIMARY KEY,
  occurred_at TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('guardian', 'teacher', 'admin', 'system', 'developer', 'unknown')),
  actor_ref TEXT,
  action TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id TEXT,
  metadata_json TEXT,
  environment TEXT NOT NULL CHECK (environment IN ('production', 'staging', 'local')),
  is_test INTEGER NOT NULL DEFAULT 0 CHECK (is_test IN (0, 1)),
  test_run_id TEXT,
  created_at TEXT NOT NULL,
  CHECK (length(trim(action)) > 0),
  CHECK (length(trim(subject_type)) > 0),
  CHECK (metadata_json IS NULL OR json_valid(metadata_json)),
  CHECK (test_run_id IS NULL OR is_test = 1)
);

CREATE INDEX idx_guardian_account_email_normalized ON guardian_account(email_normalized);
CREATE INDEX idx_guardian_account_primary_phone_normalized ON guardian_account(primary_phone_normalized);
CREATE INDEX idx_student_name_dob ON student(surname, given_name, date_of_birth);
CREATE INDEX idx_guardian_student_guardian ON guardian_student_relationship(guardian_id, status);
CREATE INDEX idx_guardian_student_student ON guardian_student_relationship(student_id, status);
CREATE INDEX idx_family_group_member_student ON family_group_member(student_id, status);
CREATE INDEX idx_academic_year_status ON academic_year(registration_status, is_current);
CREATE INDEX idx_class_session_year_stage_status ON class_session(academic_year_id, stage_code, status);
CREATE INDEX idx_pre_registration_guardian_status ON pre_registration(guardian_id, status);
CREATE INDEX idx_pre_registration_year_status ON pre_registration(academic_year_id, status);
CREATE INDEX idx_application_child_pre_registration ON application_child(pre_registration_id, status);
CREATE INDEX idx_application_child_student ON application_child(student_id, status);
CREATE INDEX idx_ranked_class_preference_child_rank ON ranked_class_preference(application_child_id, preference_rank);
CREATE INDEX idx_enrollment_class_status ON enrollment(class_session_id, status);
CREATE INDEX idx_enrollment_hold_deadline ON enrollment(effective_hold_deadline_at, status);
CREATE INDEX idx_waitlist_class_status ON waitlist_entry(class_session_id, status, preference_rank);
CREATE INDEX idx_outbound_email_status_queue ON outbound_email(status, queued_at);
CREATE INDEX idx_outbound_email_pre_registration ON outbound_email(pre_registration_id, status);
CREATE INDEX idx_audit_event_subject_time ON audit_event(subject_type, subject_id, occurred_at);
CREATE INDEX idx_audit_event_action_time ON audit_event(action, occurred_at);
