export const registrationCopy = {
  heading: "Бүртгэлийн мэдээлэл",
  intro:
    "Шинэ бүртгэлийн системийг бэлтгэж байна. Одоогоор хуучин жилийн цагийн хуваарь, төлбөр, хугацааг энэ хуудсанд одоогийн мэдээлэл мэт нийтлээгүй.",
  actionLabel: "Бүртгүүлэх",
  actionHref: "/register",
  statusLabel: "Бүртгэл нээгдэхэд энд шинэ мэдээлэл байрлана.",
};

export const registrationPrototype = {
  title: "Бүртгэл",
  description: "Наран Эрдэм сургалтын бүртгэлийн хөгжүүлэлтийн прототип.",
  notice: "Туршилтын хувилбар — энд бөглөсөн мэдээлэл хадгалагдахгүй, бүртгэл үүсэхгүй.",
};

export const registrationFormCopy = {
  selectPlaceholder: "Сонгоно уу",
  progress: {
    information: "Мэдээлэл",
    guardianRules: "Асран хамгаалагчийн журам",
    studentRules: "Сурагчийн журам",
    review: "Хянах",
  },
  buttons: {
    continueToRules: "Журамтай танилцах",
    addChild: "+ Хүүхэд нэмэх",
    removeChild: "Хасах",
    close: "Хаах",
    acknowledgeGuardian: "Уншиж танилцаж, зөвшөөрөв",
    acknowledgeStudent: "Уншиж танилцлаа",
    edit: "Мэдээлэл засах",
    finish: "Туршилтаар дуусгах",
    joinWaitlist: "Хүлээлгийн жагсаалтад орох",
  },
  guardian: {
    title: "Асран хамгаалагч",
    name: "Эцэг эх, асран хамгаалагчийн овог, нэр",
    relationship: "Хүүхдийн хэн болох",
    relationshipHelp: "Хүүхдийг зөвхөн эцэг эх эсвэл бодит асран хамгаалагч бүртгэнэ.",
    primaryPhone: "Утас",
    secondaryPhone: "2 дахь утас",
    email: "Имэйл",
    emailHelp: "Бүртгэл, төлбөр, төлөвийн чухал мэдэгдэл энэ хаягаар ирнэ.",
    facebook: "Facebook нэр",
    facebookHelp: "Ангийн Facebook группт нэгдэхэд танихад хэрэгтэй.",
    homeAddress: "Гэрийн хаягийн товч мэдээлэл",
    homeAddressHelp: "Дүүргээ бичнэ үү. Хүсвэл хороо, хотхон зэрэг мэдээлэл нэмж болно.",
    relationshipOptions: ["Ээж", "Аав", "Асран хамгаалагч"],
  },
  child: {
    title: "Хүүхэд",
    cardTitle: "Хүүхэд",
    surname: "Овог",
    name: "Нэр",
    gender: "Хүйс",
    dob: "Төрсөн огноо",
    grade: "Анги",
    school: "Сургуулийн нэр",
    returning: "Өмнө нь Наран Эрдэмд сурсан уу?",
    previousStage: "Өмнө дүүргэсэн шат",
    code: "Код",
    codePlaceholder: "Байвал оруулна уу",
    stage: "Сургалтын шат",
    stageLabels: {
      stage_1: "1-р шат — Анхан шат",
      stage_2: "2-р шат — Дунд түвшин",
      stage_3: "3-р шат — Ахисан түвшин",
    },
    genderOptions: ["Эмэгтэй", "Эрэгтэй", "Өөрөөр бичих/хэлэх"],
    gradeOptions: [
      { value: "4", label: "4-р анги" },
      { value: "5", label: "5-р анги" },
      { value: "6", label: "6-р анги" },
      { value: "7", label: "7-р анги" },
      { value: "8", label: "8-р анги" },
      { value: "9", label: "9-р анги" },
      { value: "10", label: "10-р анги" },
      { value: "other", label: "Бусад" },
    ],
    returningOptions: [
      { value: "no", label: "Үгүй" },
      { value: "yes", label: "Тийм" },
    ],
    previousStageOptions: [
      { value: "stage_1", label: "1-р шат — Анхан шат" },
      { value: "stage_2", label: "2-р шат — Дунд түвшин" },
      { value: "stage_3", label: "3-р шат — Ахисан түвшин" },
      { value: "unknown", label: "Сайн мэдэхгүй" },
    ],
  },
  classChoice: {
    title: "Анги, цаг",
    loading: "Боломжит ангиудыг авч байна…",
    unavailable: "Анги, суудлын мэдээлэл одоогоор түр боломжгүй байна.",
    noSessions: "Энэ шатны анги, цаг хараахан ороогүй байна.",
    noAvailableClass: "Энэ шатанд одоогоор сул суудалтай анги алга байна.",
    selectRequired: "Анги, цагаа сонгоно уу.",
    remainingSeats: "Сул суудал: {count}",
    full: "Анги дүүрсэн",
    activeHolds: "Түр хадгалагдсан: {count}",
    unavailableSession: "Одоогоор сонгох боломжгүй",
    waitlistRequired: "Хүлээлгийн жагсаалтаас нэг анги сонгоно уу.",
  },
  payment: {
    title: "Төлбөрийн сонголт",
    help: "Одоогийн үнийг энд оруулаагүй. Тухайн жилийн үнэ, хугацаа дараа нь тусдаа гарна.",
    planLegend: "Төлбөрийн хэлбэр",
  },
  review: {
    title: "Хянаж баталгаажуулах",
    help: "Доорх хураангуйг шалгана уу. Энэ нь илгээгдэхгүй, хадгалагдахгүй.",
    guardianHeading: "Асран хамгаалагч",
    childHeading: "Хүүхэд, анги",
    paymentHeading: "Төлбөрийн сонголт",
    codeHeading: "Код",
    selectedClassHeading: "Одоогийн сонгосон анги",
    waitlistHeading: "Хүлээлгийн жагсаалт",
    acknowledgementHeading: "Журам",
    guardianAcknowledged: "Асран хамгаалагчийн журамтай танилцсан",
    studentAcknowledged: "Сурагчийн журамтай танилцсан",
  },
  messages: {
    requiredError: "Дутуу эсвэл буруу бөглөсөн талбарыг шалгана уу.",
    prototypeComplete:
      "Бүртгэлийн шинэ системийг бэлтгэж байна. Энэ үйлдлээр бодит бүртгэл, суудал барилт, төлбөрийн хүсэлт үүсэхгүй.",
    notSelected: "Сонгоогүй",
  },
  draft: {
    title: "Хадгалсан ноорог байна",
    help: "Энэ хөтөч дээр өмнө бөглөсөн мэдээлэл түр хадгалагдсан байна. Энэ нь анги, суудал хадгалахгүй.",
    restore: "Үргэлжлүүлэн бөглөх",
    discard: "Устгах",
  },
};
